---
#
# Ansible managed
#
repository:
  description: Set up backup to remote machine using Borg and Borgmatic.
  homepage: https://buluma.github.io/
  topics: backup, ansible, molecule, tox, playbook, hacktoberfest
