---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap

  pre_tasks:
    - name: Set ssh server package name for non-Archlinux ansible_os_family
      ansible.builtin.set_fact:
        openssh_package: "openssh-server"
      when: ansible_os_family != "Archlinux"

    - name: Set ssh server package name for Archlinux ansible_os_family
      ansible.builtin.set_fact:
        openssh_package: "openssh"
      when: ansible_os_family == "Archlinux"

    - name: Install openssh
      ansible.builtin.package:
        name: "{{ openssh_package }}"
        state: present
